# Generated by Django 2.1 on 2020-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0002_acceptedtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
